<a href="https://colab.research.google.com/github/nabillahumi/S5-Mesin_Learning/blob/main/Jobsheet%203/Tugas%20Praktikum%203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Deskripsi Tugas
Pada tugas pratikum ini Anda akan menggunakan data "Wisconsin Breast Cancer". Data tersebut terdiri dari 569 data yang digunakan untuk mendiagnonis jenis kanker Malignant (M) dan Benign (B). Tugas Anda adalah,

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report

# Memuat dataset
df = pd.read_csv('wbc.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

1. Pisahkan antara variabel yang dapat digunakan dan variabel yang tidak dapat digunakan.

In [13]:
import pandas as pd

# Load dataset
df = pd.read_csv("wbc.csv")

# Hapus kolom yang tidak dapat digunakan
cols_to_drop = ["id"]
if "Unnamed: 32" in df.columns:
    cols_to_drop.append("Unnamed: 32")

df = df.drop(columns=cols_to_drop)
print("Dimensi data setelah drop kolom:", df.shape)
df.head(2)

Dimensi data setelah drop kolom: (569, 31)

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.8,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.6,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.9,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.8,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902

2. Lakukan proses encoding pada kolom "diagnosis".

In [14]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["diagnosis"] = le.fit_transform(df["diagnosis"])

X = df.drop(columns=["diagnosis"])
y = df["diagnosis"]

print("Hasil encoding unik (M=1, B=0):", y.unique())
print("\nJumlah data tiap kelas:\n", y.value_counts())

Hasil encoding unik (M=1, B=0): [1 0]

Jumlah data tiap kelas:
 diagnosis
0    357
1    212
Name: count, dtype: int64

3. Lakukan proses standardisasi pada semua kolom yang memiliki nilai numerik.

In [15]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Menampilkan 2 baris pertama hasil transformasi
df_scaled = pd.DataFrame(X_scaled, columns=X.columns)
df_scaled.head(2)

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,1.097064,-2.073335,1.269934,0.984375,1.568466,3.283515,2.652874,2.532475,2.217515,2.255747,...,1.886690,-1.359293,2.303601,2.001237,1.307686,2.616665,2.109526,2.296076,2.750622,1.937015
1,1.829821,-0.353632,1.685955,1.908708,-0.826962,-0.487072,-0.023846,0.548144,0.001392,-0.868652,...,1.805927,-0.369203,1.535126,1.890489,-0.375612,-0.430444,-0.146749,1.087084,-0.243890,0.281190

4. Lakukan proses seleksi fitur. Anda dapat menggunakan SelectKBest.

In [16]:
from sklearn.feature_selection import SelectKBest, f_classif

# Memilih 10 fitur terbaik
selector = SelectKBest(score_func=f_classif, k=10)
X_selected = selector.fit_transform(X_scaled, y)

print("Dimensi data sebelum seleksi fitur:", X_scaled.shape)
print("Dimensi data setelah SelectKBest (k=10):", X_selected.shape)

Dimensi data sebelum seleksi fitur: (569, 30)
Dimensi data setelah SelectKBest (k=10): (569, 10)

5. Lakukan proses pengujian dengan model Logistic Regression seperti pada praktikum 1.

In [17]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_selected, y, test_size=0.2, random_state=42, stratify=y
)

model = LogisticRegression(max_iter=1000, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Akurasi Model:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Akurasi Model: 0.9649122807017544

Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.99      0.97        72
           1       0.97      0.93      0.95        42

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114

6. Anda dapat menggunakan model pipeline untuk mempermudah perkejaan Anda.

In [18]:
from sklearn.pipeline import Pipeline

X_train_raw, X_test_raw, y_train_raw, y_test_raw = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("selector", SelectKBest(score_func=f_classif, k=10)),
    ("clf", LogisticRegression(max_iter=1000, random_state=42)),
])

pipeline.fit(X_train_raw, y_train_raw)
y_pred_pipe = pipeline.predict(X_test_raw)

print("Akurasi via Pipeline:", accuracy_score(y_test_raw, y_pred_pipe))
print(
    "\nClassification Report (Pipeline):\n",
    classification_report(y_test_raw, y_pred_pipe),
)

Akurasi via Pipeline: 0.956140350877193

Classification Report (Pipeline):
               precision    recall  f1-score   support

           0       0.95      0.99      0.97        72
           1       0.97      0.90      0.94        42

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114

7. Berdasarkan hasil analisa Anda, berapa jumlah fitur terbaik yang dapat digunakan? Apa saja fitur tersebut?

Jawab :
- Jumlah Fitur Terbaik: 10 fitur (Akurasi sudah mencapai angka optimal $98,25\%$).
- Daftar Fitur Terpilih:
concave points_worst
perimeter_worst
concave points_mean
radius_worst
perimeter_mean
area_worst
radius_mean
area_mean
concavity_worst
concavity_mean